# Pré-carrega a imagem na memória
preload = /home/renatolinard/wallpaper/deton__16K.png

# Define a imagem pré-carregada como papel de parede para todos os monitores
wallpaper = , /home/renatolinard/wallpaper/deton__16K.png

# Ativa o IPC para comunicação (opcional, mas bom ter)
ipc = on
