# Pré-carrega a imagem na memória
preload = /home/renatolinard/wallpaper/Deton - 16K Surreal Wall Art.png

# Define a imagem pré-carregada como papel de parede para todos os monitores
wallpaper = , /home/renatolinard/wallpaper/Deton - 16K Surreal Wall Art.png

# Ativa o IPC para comunicação (opcional, mas bom ter)
#ipc = on
