# Pré-carrega a imagem na memória
preload = /home/renatolinard/wallpaper/arch_skull.jpg

# Define a imagem pré-carregada como papel de parede para todos os monitores
wallpaper = , /home/renatolinard/wallpaper/arch_skull.jpg

# Ativa o IPC para comunicação (opcional, mas bom ter)
ipc = on
