# ~/.config/starship.toml (Versão com sintaxe de paleta corrigida)

# 1. SELECIONA a paleta de cores que vamos definir abaixo.
palette = "kanagawa"

# 2. DEFINE a nossa paleta de cores customizada.
[palettes.kanagawa]
foreground = "#DCD7BA"
background = "#1F1F28"
blue       = "#7E9CD8"
green      = "#76946A"
red        = "#C34043"
yellow     = "#DCA561"
comment    = "#545464"
magenta    = "#957FB8"


# --- Configuração do Formato e Módulos ---

# Desativa a quebra de linha para um prompt de linha única
[line_break]
disabled = true

# Define o formato geral do prompt
format = """
$os\
$directory\
$git_branch\
$git_status\
$python\
$golang\
$rust\
$c\
$nodejs\
$php\
$java\
$character"""

# Símbolo do Sistema Operacional
[os]
disabled = false
style = "#515797" # Agora usa os nomes simples da paleta
format = "[$symbol ]($style)"

[os.symbols]
Arch = "󰣇"

# Diretório
[directory]
style = "#a67337" # Cor do texto principal
format = "[renatolinard ](#737c73)[$path]($style) " # Ícone amarelo, texto na cor principal
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Branch do Git
[git_branch]
symbol = ""
style = "bold magenta"
format = '[$symbol $branch]($style)'

# Status do Git (arquivos modificados, etc.)
[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style)) '
stashed = ' *'
ahead = ' !'
behind = ' '
diverged = ' '
untracked = ' ?'
staged = ' +'
modified = ' *'
renamed = ' >'
deleted = ' -'

# Módulos de Linguagens de Programação
[python]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[c]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[rust]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[golang]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[nodejs]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[php]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[java]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

# Caractere final do prompt
[character]
success_symbol = "[](#526994)"
error_symbol = "[](#c75758)"
