# ~/.config/starship.toml (Versão Final: Ultra-Minimalista Dinâmico)

# Formato de linha única, apenas os módulos essenciais separados por um espaço.
format = """
$os\
$directory\
$git_branch\
$git_status\
$python\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$character"""

# --- Módulos com Paleta de Cores Restrita ---

[line_break]
disabled = true

# Símbolo do Sistema Operacional (cor sutil)
[os]
disabled = false
style = "bright-black" # Cinza sutil da paleta pywal
format = "[$symbol]($style) "
[os.symbols]
Arch = "󰣇"

# Username (desabilitado para um visual mais limpo)
[username]
show_always = false

# Diretório (cor de texto principal, em negrito, para destaque)
[directory]
style = "bold white" # A cor de texto mais clara da paleta pywal
format = "[ $path]($style) "
truncation_length = 4
truncation_symbol = "…/"
read_only = " "
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Branch do Git (cor sutil, a mesma do OS)
[git_branch]
symbol = ""
style = "bright-black"
format = '[$symbol $branch]($style)'

# Status do Git (cor sutil)
[git_status]
style = "bright-black"
format = '([$all_status$ahead_behind]($style)) '
# ... (símbolos de status) ...
stashed = ''
ahead = ''
behind = ''
diverged = ''
untracked = ''
staged = ''
modified = ''
renamed = ''
deleted = ''


# Módulos de Linguagens (cor sutil para não poluir)
[python]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'
[c]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'
[rust]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'
[golang]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'
[nodejs]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'
[php]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'
[java]
symbol = ""
style = "bright-black"
format = '[${symbol}(${version} )]($style)'

# Caractere final do prompt
[character]
success_symbol = "[❯](bright-black)" # Seta cinza para sucesso
error_symbol = "[❯](bold red)" # Mantemos o vermelho para erros
