# ~/.config/starship.toml (Versão Dinâmica com Pywal)

# REMOVEMOS a seleção de paleta. O Starship agora usará as cores do terminal.

# --- Configuração do Formato e Módulos ---
# Desativa a quebra de linha para um prompt de linha única
[line_break]
disabled = true

# Define o formato geral do prompt
format = """
$os\
$directory\
$git_branch\
$git_status\
$python\
$golang\
$rust\
$c\
$nodejs\
$php\
$java\
$character"""

# Símbolo do Sistema Operacional
[os]
disabled = false
style = "blue" # Cor genérica do terminal
format = "[$symbol ]($style)"

[os.symbols]
Arch = " "

# Diretório
[directory]
style = "cyan" # Cor genérica do terminal
format = "[ $path]($style) "
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Branch do Git
[git_branch]
symbol = ""
style = "bold purple" # "magenta" no ANSI é "purple"
format = '[$symbol $branch]($style)'

# Status do Git (arquivos modificados, etc.)
[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style)) '
stashed = ' *'
ahead = ' !'
behind = ' '
diverged = ' '
untracked = ' ?'
staged = ' +'
modified = ' *'
renamed = ' >'
deleted = ' -'

# Módulos de Linguagens de Programação
[python]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[c]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[rust]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[golang]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[nodejs]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[php]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

[java]
symbol = " "
style = "bold green"
format = '[${symbol}(${version} )]($style)'

# Caractere final do prompt
[character]
success_symbol = "[](bold blue)"
error_symbol = "[](bold red)"

